import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stairs(props) {
  const { nodes, materials } = useGLTF('/models/scaffold_stairs_steel_construction.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2371.287, -34.553, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_1_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_44_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_50_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_51_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_52_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_53_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_54_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_56_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_57_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_58_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_59_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_60_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_61_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_63_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_64_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_65_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_66_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_67_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_68_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_69_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_70_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_71_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_72_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_73_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_74_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_75_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_76_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_77_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_78_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_79_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_80_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_81_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_82_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_83_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_84_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_85_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_86_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_87_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_88_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_89_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_90_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_91_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_92_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_93_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_94_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_95_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_96_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_97_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_98_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_99_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_100_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_101_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_102_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_103_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_104_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_105_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_106_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_107_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_108_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_109_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_110_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_111_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_112_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_113_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_114_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_115_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_116_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_117_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_118_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_119_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_120_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_121_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_122_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_123_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_124_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_125_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_126_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_127_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_128_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_129_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_130_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_131_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_132_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_133_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_134_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_135_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_136_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_137_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_138_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_139_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_140_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_141_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_142_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_143_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_144_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_145_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_146_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_147_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_148_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_149_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_150_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_151_Material_2_0.geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_152_Material_2_0.geometry}
            material={materials.Material_2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scaffold_stairs_steel_construction.glb')